name: apk
description: A simple command-line application.
version: 1.0.0
# homepage: https://www.example.com

environment:
  sdk: ^2.8.0
  

dependencies:
  path: ^1.7.0
  args: ^1.6.0
  dio: ^3.0.10

dev_dependencies:
  pedantic: ^1.9.0

# 将脚本注册为可执行程序,可以注册多个
# 包名: 脚本名称
# 命令名称就是包名，如注册 apk: main ,在命令行中直接运行apk <commond> [args]
executables:
  apk: main
  cert: cert
  pgy: pgy